export const vietnamCities = [
  { label: "Hà Nội", value: "Ha Noi" },
  { label: "TP Hồ Chí Minh", value: "Ho Chi Minh City" },
  { label: "Đà Nẵng", value: "Da Nang" },
  { label: "Hải Phòng", value: "Hai Phong" },
  { label: "Cần Thơ", value: "Can Tho" },

  { label: "An Giang", value: "Long Xuyen" },
  { label: "Bà Rịa - Vũng Tàu", value: "Vung Tau" },
  { label: "Bắc Giang", value: "Bac Giang" },
  { label: "Bắc Kạn", value: "Bac Kan" },
  { label: "Bạc Liêu", value: "Bac Lieu" },
  { label: "Bắc Ninh", value: "Bac Ninh" },
  { label: "Bến Tre", value: "Ben Tre" },
  { label: "Bình Định", value: "Quy Nhon" },
  { label: "Bình Dương", value: "Thu Dau Mot" },
  { label: "Bình Phước", value: "Dong Xoai" },
  { label: "Bình Thuận", value: "Phan Thiet" },
  { label: "Cà Mau", value: "Ca Mau" },
  { label: "Cao Bằng", value: "Cao Bang" },
  { label: "Đắk Lắk", value: "Buon Ma Thuot" },
  { label: "Đắk Nông", value: "Gia Nghia" },
  { label: "Điện Biên", value: "Dien Bien Phu" },
  { label: "Đồng Nai", value: "Bien Hoa" },
  { label: "Đồng Tháp", value: "Cao Lanh" },
  { label: "Gia Lai", value: "Pleiku" },
  { label: "Hà Giang", value: "Ha Giang" },
  { label: "Hà Nam", value: "Phu Ly" },
  { label: "Hà Tĩnh", value: "Ha Tinh" },
  { label: "Hải Dương", value: "Hai Duong" },
  { label: "Hậu Giang", value: "Vi Thanh" },
  { label: "Hòa Bình", value: "Hoa Binh" },
  { label: "Hưng Yên", value: "Hung Yen" },
  { label: "Khánh Hòa", value: "Nha Trang" },
  { label: "Kiên Giang", value: "Rach Gia" },
  { label: "Kon Tum", value: "Kon Tum" },
  { label: "Lai Châu", value: "Lai Chau" },
  { label: "Lâm Đồng", value: "Da Lat" },
  { label: "Lạng Sơn", value: "Lang Son" },
  { label: "Lào Cai", value: "Lao Cai" },
  { label: "Long An", value: "Tan An" },
  { label: "Nam Định", value: "Nam Dinh" },
  { label: "Nghệ An", value: "Vinh" },
  { label: "Ninh Bình", value: "Ninh Binh" },
  { label: "Ninh Thuận", value: "Phan Rang" },
  { label: "Phú Thọ", value: "Viet Tri" },
  { label: "Phú Yên", value: "Tuy Hoa" },
  { label: "Quảng Bình", value: "Dong Hoi" },
  { label: "Quảng Nam", value: "Tam Ky" },
  { label: "Quảng Ngãi", value: "Quang Ngai" },
  { label: "Quảng Ninh", value: "Ha Long" },
  { label: "Quảng Trị", value: "Dong Ha" },
  { label: "Sóc Trăng", value: "Soc Trang" },
  { label: "Sơn La", value: "Son La" },
  { label: "Tây Ninh", value: "Tay Ninh" },
  { label: "Thái Bình", value: "Thai Binh" },
  { label: "Thái Nguyên", value: "Thai Nguyen" },
  { label: "Thanh Hóa", value: "Thanh Hoa" },
  { label: "Thừa Thiên Huế", value: "Hue" },
  { label: "Tiền Giang", value: "My Tho" },
  { label: "Trà Vinh", value: "Tra Vinh" },
  { label: "Tuyên Quang", value: "Tuyen Quang" },
  { label: "Vĩnh Long", value: "Vinh Long" },
  { label: "Vĩnh Phúc", value: "Vinh Yen" },
  { label: "Yên Bái", value: "Yen Bai" }
];