name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: List project files
      run: ls -R

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean compile
      working-directory: ./Backend/demo   # trỏ đúng folder chứa pom.xml

    - name: Run Tests
      run: mvn test
      working-directory: ./Backend/demo

    # Tạm thời bỏ dependency submission nếu gây lỗi
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@v4
    #   with:
    #     directory: ./Backend/demo
