name: Java CI with Maven

on:
  push:
    branches: [ "main" ]  # chạy khi push lên nhánh main
  pull_request:
    branches: [ "main" ]  # chạy khi có PR vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # môi trường runner Ubuntu

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    # Debug: In ra danh sách file để chắc chắn pom.xml nằm ở đâu
    - name: List project files
      run: ls -R

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build project (chạy trong thư mục backend)
    - name: Build with Maven
      run: mvn -B package
      working-directory: ./backend   # đổi lại nếu pom.xml ở chỗ khác

    # Run tests
    - name: Run Tests
      run: mvn test
      working-directory: ./backend

    # Optional: Update dependency graph (Dependabot support)
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
      with:
        directory: ./backend   # chỉ định đúng thư mục chứa pom.xml
